name: mainnet

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!docker/testnet*'
      - '!subgraph.testnet.yaml'
      - '!subgraph.yaml'
  workflow_dispatch:

jobs:
  build-only:
    if: github.event_name == 'pull_request'
    uses: realiotech/workflows/.github/workflows/docker.yaml@main
    with:
      DEPLOY: false
      ENVIRONMENT: prod
      PUSH: false
      RUN_NUMBER: ${{ github.run_number }}
      SHA: ${{ github.sha }}
  build-and-deploy:
    if: github.event_name != 'pull_request'
    uses: realiotech/workflows/.github/workflows/docker.yaml@main
    with:
      DEPLOY: true
      ENVIRONMENT: prod
      IMAGE_NAME: dstrx-subgraph
      MANIFEST_PATH: explorer-graph-node/base/dstrx-subgraph-job.yaml
      PUSH: true
      RUN_NUMBER: ${{ github.run_number }}
      SHA: ${{ github.sha }}
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
      REGISTRY_PASSWORD: ${{ secrets.DO_REGISTRY_PASSWORD_PROD }}
