name: mainnet

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!docker/testnet*'
      - '!subgraph.testnet.yaml'
      - '!subgraph.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!docker/testnet*'
      - '!subgraph.testnet.yaml'
      - '!subgraph.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Login to Digital Ocean Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ vars.DO_IMAGE_REGISTRY_URL }}
          username: ${{ vars.DO_IMAGE_REGISTRY_USER }}
          password: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: GitHub Actions Cache Docker layers
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.workflow }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ github.workflow }}-buildx-${{ github.sha }}
            ${{ github.workflow }}
      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          push: true
          tags: ${{ vars.DO_IMAGE_REGISTRY_URL }}/kubernetes-prod/dstrx-subgraph:${{ github.sha }}-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/mainnet.Dockerfile
  update-gitops:
    if: github.event_name != 'pull_request'
    needs: build
    environment: prod
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout gitops repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        token: ${{ secrets.GITOPS_PAT }}
        repository: realiotech/gitops
        ref: main
    - name: Update Kubernetes manifest
      run: |
        if cat explorer-graph-node/overlays/prod/dstrx-subgraph-job.yaml | grep ${{ github.sha }}-${{ github.run_number }}; then
          echo "Image tag already exists in the manifest"
          exit 0
        fi
        sed -i 's|image: .*$|image: '"registry.digitalocean.com/kubernetes-prod/dstrx-subgraph:${{ github.sha }}-${{ github.run_number }}"'|' explorer-graph-node/overlays/prod/dstrx-subgraph-job.yaml
        git config user.name 'github-actions-bot'
        git config user.email 'devops@realio.fund'
        git add .
        git commit -m 'Update image tag to ${{ github.sha }}-${{ github.run_number }}'
        git pull --rebase
        git push
    env:
      GITHUB_TOKEN: ${{ secrets.GITOPS_PAT }}