name: testnet

on:
  push:
    branches:
      - stage
    paths:
      - '**'
      - '!.github/**'
      - '!docker/mainnet*'
      - '!subgraph.mainnet.yaml'
      - '!subgraph.yaml'
  pull_request:
    branches:
      - stage
    paths:
      - '**'
      - '!.github/**'
      - '!docker/mainnet*'
      - '!subgraph.mainnet.yaml'
      - '!subgraph.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: [blacksmith-2vcpu-ubuntu-2404]
    environment: stage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Digital Ocean Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DO_IMAGE_REGISTRY_URL }}
          username: ${{ vars.DO_IMAGE_REGISTRY_USER }}
          password: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: GitHub Actions Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.workflow }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ github.workflow }}-buildx-${{ github.sha }}
            ${{ github.workflow }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DO_IMAGE_REGISTRY_URL }}/kubernetes-stage/dstrx-subgraph:${{ github.sha }}-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/testnet.Dockerfile
  update-gitops:
    if: github.event_name != 'pull_request'
    needs: build
    environment: stage
    runs-on: [blacksmith-2vcpu-ubuntu-2404]
    steps:
    - name: Checkout gitops repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITOPS_PAT }}
        repository: realiotech/gitops
        ref: main
    - name: Update Kubernetes manifest
      run: |
        if cat explorer-graph-node/base/dstrx-subgraph-job.yaml | grep ${{ github.sha }}-${{ github.run_number }}; then
          echo "Image tag already exists in the manifest"
          exit 0
        fi
        sed -i 's|image: .*$|image: '"registry.digitalocean.com/kubernetes-stage/dstrx-subgraph:${{ github.sha }}-${{ github.run_number }}"'|' explorer-graph-node/base/dstrx-subgraph-job.yaml
        git config user.name 'github-actions-bot'
        git config user.email 'devops@realio.fund'
        git add .
        git commit -m 'Update image tag to ${{ github.sha }}-${{ github.run_number }}'
        git pull --rebase
        git push
    env:
      GITHUB_TOKEN: ${{ secrets.GITOPS_PAT }}